-- CreateTable
CREATE TABLE "USERS" (
    "USERS_ID" SERIAL NOT NULL,
    "username" VARCHAR(20) NOT NULL,
    "Real_name" VARCHAR(50) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(20) NOT NULL DEFAULT 'user',
    "Profile_IMG" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("USERS_ID")
);

-- CreateTable
CREATE TABLE "CHATS" (
    "CHAT_ID" SERIAL NOT NULL,
    "TITLE_CHAT" VARCHAR(50) NOT NULL,
    "USERS_ID" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CHATS_pkey" PRIMARY KEY ("CHAT_ID")
);

-- CreateTable
CREATE TABLE "MESSAGES" (
    "MESSAGE_ID" SERIAL NOT NULL,
    "CHAT_ID" INTEGER NOT NULL,
    "role" VARCHAR(20) NOT NULL,
    "MESSAGES_CONTENT" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MESSAGES_pkey" PRIMARY KEY ("MESSAGE_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_username_key" ON "USERS"("username");

-- CreateIndex
CREATE INDEX "USERS_username_idx" ON "USERS"("username");

-- CreateIndex
CREATE INDEX "USERS_Real_name_idx" ON "USERS"("Real_name");

-- CreateIndex
CREATE INDEX "CHATS_USERS_ID_idx" ON "CHATS"("USERS_ID");

-- CreateIndex
CREATE INDEX "CHATS_TITLE_CHAT_idx" ON "CHATS"("TITLE_CHAT");

-- CreateIndex
CREATE INDEX "CHATS_updatedAt_idx" ON "CHATS"("updatedAt");

-- CreateIndex
CREATE INDEX "MESSAGES_CHAT_ID_idx" ON "MESSAGES"("CHAT_ID");

-- CreateIndex
CREATE INDEX "MESSAGES_createdAt_idx" ON "MESSAGES"("createdAt");

-- AddForeignKey
ALTER TABLE "CHATS" ADD CONSTRAINT "CHATS_USERS_ID_fkey" FOREIGN KEY ("USERS_ID") REFERENCES "USERS"("USERS_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGES" ADD CONSTRAINT "MESSAGES_CHAT_ID_fkey" FOREIGN KEY ("CHAT_ID") REFERENCES "CHATS"("CHAT_ID") ON DELETE CASCADE ON UPDATE CASCADE;
